# Generated by Django 6.0 on 2026-04-02 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingbooking',
            name='client_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
