# Generated by Django 6.0 on 2026-04-02 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_pendingbooking_client_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingbooking',
            name='raw_booking_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pendingbooking',
            name='duffel_order_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
