# Generated by Django 6.0.3 on 2026-04-20 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PendingStayBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_id', models.CharField(help_text='Duffel Stays Quote ID', max_length=255)),
                ('duffel_booking_id', models.CharField(blank=True, help_text='Duffel Stays Booking ID (Confirmed)', max_length=255, null=True)),
                ('payment_intent_id', models.CharField(help_text='Duffel Payment Intent ID', max_length=255)),
                ('client_token', models.CharField(help_text='Token for Duffel UI Component', max_length=1000)),
                ('whatsapp_number', models.CharField(max_length=50)),
                ('raw_booking_data', models.JSONField(help_text='Stores guests, email, phone number, etc required for final booking')),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('paid', 'Paid & Confirmed'), ('failed', 'Failed')], default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
