# Generated by Django 6.0 on 2026-03-29 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('profile_name', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_pic_url', models.URLField(blank=True, null=True)),
                ('last_interaction', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'WhatsApp Contact',
                'verbose_name_plural': 'WhatsApp Contacts',
            },
        ),
        migrations.CreateModel(
            name='PendingBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_id', models.CharField(max_length=255)),
                ('passenger_data', models.JSONField()),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='whatsapp.whatsappcontact')),
            ],
            options={
                'verbose_name': 'Pending Booking',
                'verbose_name_plural': 'Pending Bookings',
            },
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('in', 'Incoming'), ('out', 'Outgoing')], max_length=3)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document'), ('sticker', 'Sticker'), ('location', 'Location'), ('reaction', 'Reaction')], default='text', max_length=20)),
                ('body', models.TextField(blank=True, null=True)),
                ('media_id', models.CharField(blank=True, max_length=255, null=True)),
                ('media_url', models.URLField(blank=True, null=True)),
                ('media_mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('wa_message_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed')], default='sent', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='whatsapp.whatsappcontact')),
            ],
            options={
                'verbose_name': 'WhatsApp Message',
                'verbose_name_plural': 'WhatsApp Messages',
                'ordering': ['-timestamp'],
            },
        ),
    ]
